artifact_uri: /workspace/mlruns/a516ab04d67d47e9b5c024c810adf82d/artifacts
end_time: null
entry_point_name: ''
experiment_id: '407750921781669166'
lifecycle_stage: active
run_id: a516ab04d67d47e9b5c024c810adf82d
run_name: lr_baseline
source_name: ''
source_type: 4
source_version: ''
start_time: 1751744092435
status: 1
tags: []
user_id: root
