aliases: []
creation_timestamp: 1751739862825
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1751739862825
metrics: null
model_id: m-d7820252477749708b068afa72abaadd
name: iris_random_forest
params: null
run_id: 91da3a827a5346e185bd0ef75beed61d
run_link: null
source: models:/m-d7820252477749708b068afa72abaadd
status: READY
status_message: null
storage_location: file:///workspace/mlruns_local/0/models/m-d7820252477749708b068afa72abaadd/artifacts
user_id: null
version: 1
