artifact_uri: file:///c:/docker_projects/docker_dev_template/notebooks/mlflow/305556046869090519/45de310e9b6b4daca4ca9b5d0b0861c5/artifacts
end_time: 1750368148177
entry_point_name: ''
experiment_id: '305556046869090519'
lifecycle_stage: active
run_id: 45de310e9b6b4daca4ca9b5d0b0861c5
run_name: amusing-bug-40
source_name: ''
source_type: 4
source_version: ''
start_time: 1750368148122
status: 3
tags: []
user_id: ghadf
