aliases: []
creation_timestamp: 1751742334294
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1751742334294
metrics: null
model_id: m-201422c209804e12a14ac467e6e5a7a3
name: iris_logreg
params: null
run_id: f101615ae70642f9b3128f8fa13880d6
run_link: null
source: models:/m-201422c209804e12a14ac467e6e5a7a3
status: READY
status_message: null
storage_location: /workspace/mlruns/models/m-201422c209804e12a14ac467e6e5a7a3/artifacts
user_id: null
version: 6
