aliases: []
creation_timestamp: 1751741070221
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1751741070221
metrics: null
model_id: m-7e1b7bfb67b6463fb34ef7183c477fbd
name: iris_logreg
params: null
run_id: fa9f4e32c9b345b0a66e778dc4681004
run_link: null
source: models:/m-7e1b7bfb67b6463fb34ef7183c477fbd
status: READY
status_message: null
storage_location: /workspace/mlruns/models/m-7e1b7bfb67b6463fb34ef7183c477fbd/artifacts
user_id: null
version: 3
