version: '3.8'

services:
  datascience:
    build: 
      context: .  # Ensure the build context is the current directory
      dockerfile: .devcontainer/Dockerfile  # Ensure the Dockerfile is specified correctly
    volumes:
      - .:/workspace
    ports:
      - "8888:8888"  # For Jupyter Notebook
      - "6006:6006"  # For TensorBoard
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia  # Specify NVIDIA driver for GPU support
              count: all  # Use all available GPUs
              capabilities: [gpu]  # Set capabilities to GPU
    environment:
      - ENV_NAME=python_tutorial  # Set environment variables
      - PYTHON_VER=3.10
    command: ["conda", "run", "-n", "data_science", "jupyter", "lab", "--ip", "0.0.0.0", "--port", "8888", "--no-browser", "--allow-root"]
