[build]
base = "frontend"
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18.20.0"
VITE_API_URL = "https://docker-dev-template.onrender.com/api/v1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 
