artifact_uri: file:///c:/docker_projects/docker_dev_template/notebooks/mlflow/305556046869090519/1abe58fe4cbd403fbfbcae58589300d1/artifacts
end_time: 1750368148731
entry_point_name: ''
experiment_id: '305556046869090519'
lifecycle_stage: active
run_id: 1abe58fe4cbd403fbfbcae58589300d1
run_name: whimsical-mole-673
source_name: ''
source_type: 4
source_version: ''
start_time: 1750368148688
status: 3
tags: []
user_id: ghadf
