digest: d32b17d8
name: dataset
profile: '{"features_shape": [5, 4], "features_size": 20, "features_nbytes": 160}'
schema: '{"mlflow_tensorspec": {"features": "[{\"type\": \"tensor\", \"tensor-spec\":
  {\"dtype\": \"float64\", \"shape\": [-1, 4]}}]", "targets": null}}'
source: '{"tags": {"mlflow.user": "root", "mlflow.source.name": "/app/.venv/lib/python3.10/site-packages/ipykernel_launcher.py",
  "mlflow.source.type": "LOCAL"}}'
source_type: code
