aliases: []
creation_timestamp: 1751743028461
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1751743028461
metrics: null
model_id: m-f23abad860744fd18f299681bc3140b2
name: iris_random_forest
params: null
run_id: f32d6b50b1cd4285a58c6e9e50eb8a47
run_link: null
source: models:/m-f23abad860744fd18f299681bc3140b2
status: READY
status_message: null
storage_location: /workspace/mlruns/models/m-f23abad860744fd18f299681bc3140b2/artifacts
user_id: null
version: 2
