artifact_uri: file:///c:/docker_projects/docker_dev_template/notebooks/mlflow/305556046869090519/2570e306b48a40418b5baa8dbb1212a2/artifacts
end_time: 1750368151628
entry_point_name: ''
experiment_id: '305556046869090519'
lifecycle_stage: active
run_id: 2570e306b48a40418b5baa8dbb1212a2
run_name: random_forest_optimization
source_name: ''
source_type: 4
source_version: ''
start_time: 1750368147776
status: 3
tags: []
user_id: ghadf
