aliases: []
creation_timestamp: 1751744100595
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1751744100595
metrics: null
model_id: m-9f425f7c087142d49c9dd65c57730188
name: iris_logreg
params: null
run_id: a516ab04d67d47e9b5c024c810adf82d
run_link: null
source: models:/m-9f425f7c087142d49c9dd65c57730188
status: READY
status_message: null
storage_location: /workspace/mlruns/models/m-9f425f7c087142d49c9dd65c57730188/artifacts
user_id: null
version: 8
