artifact_location: file:///c:/docker_projects/docker_dev_template/notebooks/mlflow/305556046869090519
creation_time: 1750368144237
experiment_id: '305556046869090519'
last_update_time: 1750368144237
lifecycle_stage: active
name: iris_classification
