aliases: []
creation_timestamp: 1751740694215
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1751740694215
metrics: null
model_id: m-d79cac578c0a4a9ab41856a50182685f
name: iris_logreg
params: null
run_id: 120af80410894643bbd3511f28f3345b
run_link: null
source: models:/m-d79cac578c0a4a9ab41856a50182685f
status: READY
status_message: null
storage_location: /workspace/mlruns/models/m-d79cac578c0a4a9ab41856a50182685f/artifacts
user_id: null
version: 2
