artifact_location: file:///c:/docker_projects/docker_dev_template/notebooks/mlflow/0
creation_time: 1750368144229
experiment_id: '0'
last_update_time: 1750368144229
lifecycle_stage: active
name: Default
