aliases: []
creation_timestamp: 1751747465140
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1751747465140
metrics: null
model_id: m-fbd83bcf33ea45019899a2ca53ed25b1
name: iris_logreg
params: null
run_id: dfed82380704425e95459dd31fa52844
run_link: null
source: models:/m-fbd83bcf33ea45019899a2ca53ed25b1
status: READY
status_message: null
storage_location: /workspace/mlruns/models/m-fbd83bcf33ea45019899a2ca53ed25b1/artifacts
user_id: null
version: 11
