artifact_uri: file:///c:/docker_projects/docker_dev_template/notebooks/mlflow/305556046869090519/9e5ac23f41f745f7b072aba3e3d93e62/artifacts
end_time: 1750368147841
entry_point_name: ''
experiment_id: '305556046869090519'
lifecycle_stage: active
run_id: 9e5ac23f41f745f7b072aba3e3d93e62
run_name: gentle-ray-857
source_name: ''
source_type: 4
source_version: ''
start_time: 1750368147799
status: 3
tags: []
user_id: ghadf
