artifact_uri: /workspace/mlruns/22111a912d4c49a1b5f1c7bf69e89a1d/artifacts
end_time: null
entry_point_name: ''
experiment_id: '407750921781669166'
lifecycle_stage: active
run_id: 22111a912d4c49a1b5f1c7bf69e89a1d
run_name: lr_baseline
source_name: ''
source_type: 4
source_version: ''
start_time: 1751741725338
status: 1
tags: []
user_id: root
