artifact_uri: file:///workspace/mlruns_local/0/89b970151f1549c5a561954004094cf4/artifacts
deleted_time: null
end_time: null
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 89b970151f1549c5a561954004094cf4
run_name: cancer_bayes
source_name: ''
source_type: 4
source_version: ''
start_time: 1751739865916
status: 1
tags: []
user_id: root
