aliases: []
creation_timestamp: 1751739865611
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1751739865611
metrics: null
model_id: m-83882794e36a4c6eb37f9bf1f942c2ce
name: iris_logreg
params: null
run_id: 3fdc0d60f91647e4beeee8361041970a
run_link: null
source: models:/m-83882794e36a4c6eb37f9bf1f942c2ce
status: READY
status_message: null
storage_location: file:///workspace/mlruns_local/0/models/m-83882794e36a4c6eb37f9bf1f942c2ce/artifacts
user_id: null
version: 1
