services:
  - type: web
    name: nfl-kicker-api
    env: node
    plan: free
    rootDir: src/backend
    buildCommand: "npm ci --omit=dev"
    startCommand: "node server.js"
    healthCheckPath: /api/ping    # Render watches this
    autoDeploy: true
    envVars:
      - key: CORS_ORIGIN
        value: "https://<your-site>.netlify.app"
      - key: NODE_ENV
        value: production
