artifact_uri: file:///c:/docker_projects/docker_dev_template/notebooks/mlflow/305556046869090519/a57f3dd3b92a4fafb75e6ff806db3f4f/artifacts
end_time: 1750368149052
entry_point_name: ''
experiment_id: '305556046869090519'
lifecycle_stage: active
run_id: a57f3dd3b92a4fafb75e6ff806db3f4f
run_name: unique-fowl-309
source_name: ''
source_type: 4
source_version: ''
start_time: 1750368148994
status: 3
tags: []
user_id: ghadf
