aliases: []
creation_timestamp: 1751745947245
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1751745947245
metrics: null
model_id: m-43a619a93d5b496e936a1d568f277c62
name: iris_logreg
params: null
run_id: 9ffebb70e016463196cc0f543f149eb2
run_link: null
source: models:/m-43a619a93d5b496e936a1d568f277c62
status: READY
status_message: null
storage_location: /workspace/mlruns/models/m-43a619a93d5b496e936a1d568f277c62/artifacts
user_id: null
version: 10
