artifact_uri: /workspace/mlruns/ca00350f3ee8491e962ce4bf2fbb90c5/artifacts
end_time: null
entry_point_name: ''
experiment_id: '407750921781669166'
lifecycle_stage: active
run_id: ca00350f3ee8491e962ce4bf2fbb90c5
run_name: lr_baseline
source_name: ''
source_type: 4
source_version: ''
start_time: 1751754253927
status: 1
tags: []
user_id: root
