aliases: []
creation_timestamp: 1751741732047
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1751741732047
metrics: null
model_id: m-f0fce6b86f0d478c9a47a11e2e42ed09
name: iris_logreg
params: null
run_id: 22111a912d4c49a1b5f1c7bf69e89a1d
run_link: null
source: models:/m-f0fce6b86f0d478c9a47a11e2e42ed09
status: READY
status_message: null
storage_location: /workspace/mlruns/models/m-f0fce6b86f0d478c9a47a11e2e42ed09/artifacts
user_id: null
version: 4
