artifact_uri: file:///c:/docker_projects/docker_dev_template/notebooks/mlflow/305556046869090519/e78df81e34a547688226eaefff1d5f20/artifacts
end_time: 1750368148244
entry_point_name: ''
experiment_id: '305556046869090519'
lifecycle_stage: active
run_id: e78df81e34a547688226eaefff1d5f20
run_name: enchanting-snake-567
source_name: ''
source_type: 4
source_version: ''
start_time: 1750368148184
status: 3
tags: []
user_id: ghadf
