aliases: []
creation_timestamp: 1751743567619
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1751743567619
metrics: null
model_id: m-aa6219e1d18e4045a9da6ebdb53a107b
name: iris_logreg
params: null
run_id: 1e0f0e2ec7b4450dbc1df77821d23610
run_link: null
source: models:/m-aa6219e1d18e4045a9da6ebdb53a107b
status: READY
status_message: null
storage_location: /workspace/mlruns/models/m-aa6219e1d18e4045a9da6ebdb53a107b/artifacts
user_id: null
version: 7
