artifact_uri: /workspace/mlruns/fa9f4e32c9b345b0a66e778dc4681004/artifacts
end_time: null
entry_point_name: ''
experiment_id: '407750921781669166'
lifecycle_stage: active
run_id: fa9f4e32c9b345b0a66e778dc4681004
run_name: lr_baseline
source_name: ''
source_type: 4
source_version: ''
start_time: 1751741064227
status: 1
tags: []
user_id: root
