artifact_uri: /workspace/mlruns/1e0f0e2ec7b4450dbc1df77821d23610/artifacts
end_time: null
entry_point_name: ''
experiment_id: '407750921781669166'
lifecycle_stage: active
run_id: 1e0f0e2ec7b4450dbc1df77821d23610
run_name: lr_baseline
source_name: ''
source_type: 4
source_version: ''
start_time: 1751743560343
status: 1
tags: []
user_id: root
