aliases: []
creation_timestamp: 1751742190934
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1751742190934
metrics: null
model_id: m-1c25bf0473a7493e8587ceb07b4c8647
name: iris_logreg
params: null
run_id: 2fb64eafcdef48feaefd895d92add1ef
run_link: null
source: models:/m-1c25bf0473a7493e8587ceb07b4c8647
status: READY
status_message: null
storage_location: /workspace/mlruns/models/m-1c25bf0473a7493e8587ceb07b4c8647/artifacts
user_id: null
version: 5
